### ISSUE TITLE
feature: Improvement to PhpGetSet

### ISSUE THREAD

**Issue by messatsuu** [ccaglak/phptools.nvim#2]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Currently, when using `PhpGetSet`, the implementation already seems to work in various aspects, but I think it could use a few improvements.

Some things that I've noticed:
- The command throws an error once the type is nullable (e.g. `?string`).
- Formatting seems a bit weird in some cases and could be improved with better indenting and use of spaces.
- When a  getter/setter already exists, the function could notify the user of that, instead of creating a new one.
- Lack of a Function that generates missing getters/setters for *all* properties inside a class. 

### Describe the solution you'd like

I think these things should be feasible to implement. I'm open to the idea of making a few PRs myself (since I think the project has great potential), but they'd have to be properly reviewed, since I'm relatively inexperienced with Lua.

### Describe alternatives you've considered

I've considered cloning this repo since I wasn't sure if it is actively maintained anymore (and idk if anyone wants to look at my lua-code in their free time), but I think a project like this holds great value and implements a few features that I think are otherwise missing from Neovim's PHP integration : )

**Comment by ccaglak** [comment]
Hi Nicholas, 
i was away, however welcome to submit a pr.  

1. The command throws an error once the type is nullable (e.g. ?string).
2. Formatting seems a bit weird in some cases and could be improved with better indenting and use of spaces.
3. When a getter/setter already exists, the function could notify the user of that, instead of creating a new one.
4. Lack of a Function that generates missing getters/setters for all properties inside a class.

1-3 is doable but 4 might not be a good idea since not all properties require getter/setters.

**Comment by ccaglak** [comment]
1 is done, 2 is done in a manual way for now.

**Comment by ccaglak** [comment]
3. done
